version: '3.7'
services:
  database:
    image: mariadb:10.5.8
    container_name: database
    hostname: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=movistar
      - MYSQL_USER=telefonica
      - MYSQL_PASSWORD=vass
    ports:
    - "3306:3306"
    volumes:
    - ~/database/storage/mariadb/vass/telefonica/:/var/lib/mysql:rw
    - ./database/sql/:/home/mysql/sql/:rw

  magento:
    image: telefonica/magento:0.12
    container_name: magento
    hostname: magento
    restart: always
    environment:
      DOCKER_USER: www-data
    ports:
    - "8080:80"
    depends_on:
      - database
    volumes:
    - ./source:/var/www/html/magento
    - ./etc/infrastructure/apache/default.conf:/etc/apache2/sites-available/000-default.conf

  nginx-magento:
    image: nginx:1.18.0-alpine
    container_name: "nginx-magento"
    hostname: nginx
    restart: always
    depends_on:
      - magento
    ports:
      - "80:80"
    volumes:
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
